# Generated by Django 3.1 on 2021-06-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('pot color', 'pot color'), ('plant size', 'plant size')], max_length=100),
        ),
    ]
