# Generated by Django 3.1 on 2021-06-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210623_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('pot_color', 'pot_color'), ('plant_size', 'plant_size')], max_length=100),
        ),
    ]
