# Generated by Django 3.1 on 2021-06-13 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='is_spureadmin',
            new_name='is_superadmin',
        ),
    ]
