# Generated by Django 3.1 on 2021-06-13 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_auto_20210613_1833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cart_image',
            new_name='cat_image',
        ),
    ]
